### ISSUE TITLE
apex pip install doesn't work

### ISSUE THREAD

**Issue by alfassy** [NVlabs/wetectron#10]
/dccstor/alfassy/anaconda32/envs/wetectron/lib/python3.7/site-packages/pip/_internal/commands/install.py:235: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
    Running command python setup.py egg_info

    torch.__version__  = 1.1.0

    running egg_info
    creating /tmp/pip-pip-egg-info-qt57kamg/apex.egg-info
    writing /tmp/pip-pip-egg-info-qt57kamg/apex.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-qt57kamg/apex.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-qt57kamg/apex.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-qt57kamg/apex.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-qt57kamg/apex.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-qt57kamg/apex.egg-info/SOURCES.txt'
    /tmp/pip-req-build-kx4dys3w/setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
    Running command /dccstor/alfassy/anaconda32/envs/wetectron/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-kx4dys3w/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-kx4dys3w/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-x78gny5k/install-record.txt --single-version-externally-managed --compile --install-headers /dccstor/alfassy/anaconda32/envs/wetectron/include/python3.7m/apex

    torch.__version__  = 1.1.0

    /tmp/pip-req-build-kx4dys3w/setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2019 NVIDIA Corporation
    Built on Fri_Feb__8_19:08:17_PST_2019
    Cuda compilation tools, release 10.1, V10.1.105
    from /opt/share/cuda-10.1/x86_64//bin

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-kx4dys3w/setup.py", line 152, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-kx4dys3w/setup.py", line 106, in check_cuda_torch_binary_vs_bare_metal
        "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 9.0.176.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
ERROR: Command errored out with exit status 1: /dccstor/alfassy/anaconda32/envs/wetectron/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-kx4dys3w/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-kx4dys3w/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-x78gny5k/install-record.txt --single-version-externally-managed --compile --install-headers /dccstor/alfassy/anaconda32/envs/wetectron/include/python3.7m/apex Check the logs for full command output.

seems to be a cuda mismatch, I am trying to solve it

**Comment by jason718** [comment]
also you pytorch version (1.1) seems too low.

**Comment by jason718** [comment]
seems like you cuda is 10.1 but pytorch is compiled using cuda 9.0. My guess is you are using some very old pytorch. Try Pytorch1.5+ with cuda10.1 should solve the issue.

**Comment by alfassy** [comment]
I created the env according to your install.md. I also made sure that CUDA_HOME, CUDA_BIN_PATH, PATH, LD_LIBRARY_PATH are updated

**Comment by alfassy** [comment]
It ended up being an env problem on my cluster. sorry about that
