### ISSUE TITLE
apex pip install error 

### ISSUE THREAD

**Issue by wcy1122** [NVlabs/wetectron#11]
/home/chengyao/anaconda3/envs/wetectron/lib/python3.7/site-packages/pip/_internal/commands/install.py:235: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 20.2.4 from /home/chengyao/anaconda3/envs/wetectron/lib/python3.7/site-packages/pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-fxefendb
Created temporary directory: /tmp/pip-req-tracker-e8j3jmk8
Initialized build tracking at /tmp/pip-req-tracker-e8j3jmk8
Created build tracker: /tmp/pip-req-tracker-e8j3jmk8
Entered build tracker: /tmp/pip-req-tracker-e8j3jmk8
Created temporary directory: /tmp/pip-install-07btyhmw
Processing /home/chengyao/Documents/wetectron
  Created temporary directory: /tmp/pip-req-build-eb__lacd
  Added file:///home/chengyao/Documents/wetectron to build tracker '/tmp/pip-req-tracker-e8j3jmk8'
    Running setup.py (path:/tmp/pip-req-build-eb__lacd/setup.py) egg_info for package from file:///home/chengyao/Documents/wetectron
    Created temporary directory: /tmp/pip-pip-egg-info-6d04wmnh
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-6d04wmnh/wetectron.egg-info
    writing /tmp/pip-pip-egg-info-6d04wmnh/wetectron.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-6d04wmnh/wetectron.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-6d04wmnh/wetectron.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-6d04wmnh/wetectron.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-6d04wmnh/wetectron.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-6d04wmnh/wetectron.egg-info/SOURCES.txt'
  Source in /tmp/pip-req-build-eb__lacd has version 1.0, which satisfies requirement wetectron==1.0 from file:///home/chengyao/Documents/wetectron
  Removed wetectron==1.0 from file:///home/chengyao/Documents/wetectron from build tracker '/tmp/pip-req-tracker-e8j3jmk8'
Skipping wheel build for wetectron, due to binaries being disabled for it.
Installing collected packages: wetectron
  Created temporary directory: /tmp/pip-record-3uzcfjj3
    Running command /home/chengyao/anaconda3/envs/wetectron/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-eb__lacd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-eb__lacd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-3uzcfjj3/install-record.txt --single-version-externally-managed --compile --install-headers /home/chengyao/anaconda3/envs/wetectron/include/python3.7m/wetectron
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --cpp_ext not recognized
    Running setup.py install for wetectron ... error
ERROR: Command errored out with exit status 1: /home/chengyao/anaconda3/envs/wetectron/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-eb__lacd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-eb__lacd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-3uzcfjj3/install-record.txt --single-version-externally-managed --compile --install-headers /home/chengyao/anaconda3/envs/wetectron/include/python3.7m/wetectron Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/chengyao/anaconda3/envs/wetectron/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 852, in install
    req_description=str(self.req),
  File "/home/chengyao/anaconda3/envs/wetectron/lib/python3.7/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

**Comment by jason718** [comment]
Not very sure about what happened. I would try to install without these flags, or [compile the source](https://github.com/NVIDIA/apex) instead.

Unfortunately, I'm not super familiar with apex details, you may want to ask this installation issue in their repo for better help.

**Comment by wcy1122** [comment]
ok, thanks

**Comment by jason718** [comment]
close this for now. feel free to reopen at anytime.

**Comment by wcy1122** [comment]
I don't know why, but I successfully install apex by avoid using tmux.
