### ISSUE TITLE
No ITER_SIZE value in coco configs.

### ISSUE THREAD

**Issue by alfassy** [NVlabs/wetectron#13]
Hi,
In train_net.py, inside update_iters, we use cfg.SOLVER.ITER_SIZE but this variable isn't defined in the configs, should I just add it? if so, can you suggest an optimal value for COCO training?
Thank you,
Amit

**Comment by jason718** [comment]
That's a bug in prev version. I have fixed in the latest version, please pull again.

I'm not sure about the optimal value, it's a feature added by the community.
