### ISSUE TITLE
the output dimension of cls_score and det_score is 21 

### ISSUE THREAD

**Issue by liz6688** [NVlabs/wetectron#14]
Why the output dimension of cls_score and det_score is 21？According to my understanding, the teacher network is based on the WSDDN method, and the output dimension of WSDDN is 20. Is there any reason for this? 
Thanks.

**Comment by jason718** [comment]
the 0th-dim is supposed to be `background`. This is quite common in supervised works ([detectron2_link](https://github.com/facebookresearch/detectron2/blob/05bea69b3cc5d1f36f6b1f7b074bd0d1b9bdd15b/detectron2/modeling/roi_heads/fast_rcnn.py#L36)) and also prior weakly-supervised methods ([oicr_link](https://github.com/ppengtang/oicr/blob/cd136fa4c64cadb19bc3bdf5ba4238b8a55166ca/models/VGG16/train.prototxt#L685)).

**Comment by suilin0432** [comment]
Em... , If I do not make a mistaken, it seems like in [oicr_link](https://github.com/ppengtang/oicr/blob/cd136fa4c64cadb19bc3bdf5ba4238b8a55166ca/models/VGG16/train.prototxt#L685), the output dimension of the MIL branch is also 20.
