### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by junx1992** [NVlabs/wetectron#16]
Hi, I am very interested in your work. I am running with the config file "V_16_voc07.yaml" with 4 P40.  It shows that the training should finish after more than 3 days. I am wondering why the training is so slow or whether my running is wrong.

**Comment by jason718** [comment]
something seems to be wrong. I was using 8 V100, and the training tookl 9~10h.  

I'm not sure how fast P40 runs compared to V100, but 3 days seems to be too slow.
