### ISSUE TITLE
About proposals

### ISSUE THREAD

**Issue by dejianchen1989** [NVlabs/wetectron#17]
Hi, thanks for sharing this wonderful work.

We tried to use some open source code about Selective-Search to generate proposals, but the default result is largely different from the proposals .pkl files you've provided.

Could you disclose more details about how proposals are generated, e.g. codes, hyper-parameters? Thanks a lot!

**Comment by jason718** [comment]
We didn't generate SS/MCG proposals by ourselves. The SS files are converted from the fast-rcnn provided version. You can find there original README [here](https://github.com/rbgirshick/fast-rcnn#installation-sufficient-for-the-demo), and this seems to be the original [matlab code](https://github.com/rbgirshick/rcnn/blob/master/selective_search/selective_search_boxes.m).

**Comment by Fly-dream12** [comment]
Can you give an example of how to generate the pkl file once the boxes are obtained by SS proposals.
Thanks! @jason718

**Comment by jason718** [comment]
Not exactly the one I was using, but similar: https://github.com/facebookresearch/Detectron/blob/master/tools/convert_selective_search.py

**Comment by vadimkantorov** [comment]
> We didn't generate SS/MCG proposals by ourselves. The SS files are converted from the fast-rcnn provided version. You can find there original README [here](https://github.com/rbgirshick/fast-rcnn#installation-sufficient-for-the-demo), and this seems to be the original [matlab code](https://github.com/rbgirshick/rcnn/blob/master/selective_search/selective_search_boxes.m).

And what about the MCG files? Did you compute them yourself or are they also copied from somewhere? Thank you! (basically wondering about the used MCG parameters / code)

**Comment by jason718** [comment]
@vadimkantorov we get it from here: https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/mcg/

> > We didn't generate SS/MCG proposals by ourselves. The SS files are converted from the fast-rcnn provided version. You can find there original README [here](https://github.com/rbgirshick/fast-rcnn#installation-sufficient-for-the-demo), and this seems to be the original [matlab code](https://github.com/rbgirshick/rcnn/blob/master/selective_search/selective_search_boxes.m).
> 
> And what about the MCG files? Did you compute them yourself or are they also copied from somewhere? Thank you! (basically wondering about the used MCG parameters / code)
