### ISSUE TITLE
About results：MIST+cdb，multi scale and flip testing 2007 test mAP50 is 52.2.

### ISSUE THREAD

**Issue by hu5tao** [NVlabs/wetectron#19]
Thanks for you sharing  wonderful work；
but we tried to retrain your model, config: 8GPU, base lr:0.01, multi-scale training etc. 
we have tested  all middle model including final model , top map is 52.2, we don't kown the reason. hope your reply, thanks.

**Comment by jason718** [comment]
Can you share the log? Hard to know what happened just from a number.

Also, have you tried different random seed?

**Comment by hu5tao** [comment]
sry，log can not share, seed i set 1234, this will be a great influence to that ?

**Comment by jason718** [comment]
idn, but as noted in the documents, ours does suffer from variance (1~3% is common). Seed 1234 is what we were using, but it cannot guarantee deterministic behavior. There is nor hard playing w/ it for a bit.

**Comment by hu5tao** [comment]
thank you，i found that the main inference due to cdb，no cdb is almost same with the paper; And i have a problem，you will provide COCO2017 SS proposal pkl file, i just find COCO2014. thank you, if you have, could you share it for me, 1010004295@qq.com. really thanks.

**Comment by jason718** [comment]
COCO 2014 train + COCO 2014 valminusminival = COCO 2017. see https://github.com/NVlabs/wetectron/blob/9973eb4f1716fbc5f46b41a7f93fb1f1c78bc8c7/configs/coco/V_16_coco17.yaml#L25

We have provided MCG proposals for previous two. We don't have Selective Search proposals for COCO. sorry

**Comment by hu5tao** [comment]
thank you,i got it; and something about ROIalign and ROIpoor, the ROI align results of OICR just 22-23%, why will be this?

**Comment by jason718** [comment]
interesting, I didn't know why RoI-Align performs so poor. We never used it actually, just to follow prior work.

To me, this seems to be a bug (?), or maybe some parameters are set wrong? Can you share the config?

**Comment by hu5tao** [comment]
yes , i have a try, 0 or set 2, results will be same ，just 23%, you can have a try

**Comment by swzhang5** [comment]
> thank you，i found that the main inference due to cdb，no cdb is almost same with the paper; And i have a problem，you will provide COCO2017 SS proposal pkl file, i just find COCO2014. thank you, if you have, could you share it for me, [1010004295@qq.com](mailto:1010004295@qq.com). really thanks.

Excuse me, so you set DB_METHOD to 'none', and got the same result ? I try no cdb, but the result is only 51.2.
