### ISSUE TITLE
error: expected primary-expression before ‘>’ token: input.data_ptr<scalar_t>()

### ISSUE THREAD

**Issue by deeplearning666** [NVlabs/wetectron#20]
Hello! I have much interest in your code. However, when I run "python setup.py install", I meet the question: "error: expected primary-expression before ‘>’ token: input.data_ptr<scalar_t>()" . Can you give my some suggestions? I'm looking forward to hearing from you soon!

**Comment by jason718** [comment]
seems like an apex installation issue, have you installed apex successfully?

FYI: https://github.com/NVIDIA/apex/issues/802

**Comment by deeplearning666** [comment]
Thank you for replying! Before I use wetectron, I run the commend:
cd wetectron
python setup.py install
Then I meet the following question. This seems not an issue for apex installation

**Comment by jason718** [comment]
what's you env setting? like python, pytorch, cuda, cmake version?
