### ISSUE TITLE
results are different between roi pooling and roi align

### ISSUE THREAD

**Issue by UcanSee** [NVlabs/wetectron#23]
Thanks for sharing such wonderful works！
I have used your codes to train OICR-vgg16， the mAP is 43% when I use roi-pooling.  But when I use roi align, the mAP just have 23%. Difference between this two config is only 'POOLER_METHOD',  Have you meets this problem in experiment?

**Comment by jason718** [comment]
#19 also reported this. I didn't use RoI-align in our exps, so this is also the first time I heard this. Let me take a look

**Comment by jason718** [comment]
maybe the issue is sampling_ratio?

in maskrcnn-benchmark, they set this to 2: https://github.com/facebookresearch/maskrcnn-benchmark/blob/57eec25b75144d9fb1a6857f32553e1574177daf/configs/pascal_voc/e2e_mask_rcnn_R_50_FPN_1x_cocostyle.yaml#L20

but this repo set the default value to 0: https://github.com/NVlabs/wetectron/blob/e4fc0289e8e87caa0e1c501ef8cb0123cdaf580d/wetectron/config/defaults.py#L241

So maybe try 2?

**Comment by UcanSee** [comment]
> maybe the issue is sampling_ratio?
> 
> in maskrcnn-benchmark, they set this to 2: https://github.com/facebookresearch/maskrcnn-benchmark/blob/57eec25b75144d9fb1a6857f32553e1574177daf/configs/pascal_voc/e2e_mask_rcnn_R_50_FPN_1x_cocostyle.yaml#L20
> 
> but this repo set the default value to 0:
> 
> https://github.com/NVlabs/wetectron/blob/e4fc0289e8e87caa0e1c501ef8cb0123cdaf580d/wetectron/config/defaults.py#L241
> 
> So maybe try 2?

I have tried sampling_ratio = 2， but the results have no difference.

**Comment by UcanSee** [comment]
Hello, have you conducted any experiments with FPN structure like R50-FPN?  I never see any relational experiments in recent papers.

**Comment by jason718** [comment]
We did try, but it didn't outperform vanilla ResNet-C4 model. The multi-scale setting made it overfit to small regions somehow.

**Comment by UcanSee** [comment]
> We did try, but it didn't outperform vanilla FPN model. The multi-scale setting made it overfit to small regions somehow.

what do you mean 'vanilla FPN model'?  Does it mean that performance of MIST-R50-C4 model is better than MIST-R50-FPN model?

**Comment by jason718** [comment]
sorry typo, should be vanilla ResNet-C4 models. changed my prev answers

**Comment by UcanSee** [comment]
I've got it , thank you very much!
