### ISSUE TITLE
Training log for COCO

### ISSUE THREAD

**Issue by jshi31** [NVlabs/wetectron#27]
Hi, could you share the log and training time for COCO? Now I am trying to replicate the performance of COCO, but the training time is 3 days (4 1080ti with batch size 4) and the performance is behind the reported number. Although I train with fewer batch size than yours (4 vs 8), I am wondering if another reason is that the default setting for coco in https://github.com/NVlabs/wetectron/blob/master/configs/coco/V_16_coco17.yaml does not use the concrete dropblock. So I want to compare my training log with yours to see the loss trend and time cost. Thanks!

**Comment by jason718** [comment]
The training seems to be reasonable for 4 1080ti.

My log for training vgg16 on coco14 is attached below. In total it takes 1d2h on 8 V100 GPUs.
[coco14-train-log.txt](https://github.com/NVlabs/wetectron/files/5783411/coco14-train-log.txt)
