### ISSUE TITLE
About Concrete Dropblock

### ISSUE THREAD

**Issue by hhhh12345678** [NVlabs/wetectron#28]
Hi, guys, thanks for your excellent work. 
After had a glance at your code and paper, the concrete drop block seems only be applied to proposals features. Have you try to insert your proposed module into backbone to see whether it works or not.

**Comment by jason718** [comment]
thanks!

We didn't try concrete dropblock on the feature map of the whole image. The reason is that we first found vanilla dropblock/spatial-dropout working better on RoI than Image features, we thus followed it.
