### ISSUE TITLE
Points and Scribbles.

### ISSUE THREAD

**Issue by LoveIsAGame** [NVlabs/wetectron#31]
I have a new set of data. How can I generate label information about Points and Scribbles.

**Comment by vipbze** [comment]
Did you achieve 54.9 AP on VOC07 dataset based on this git?

**Comment by jason718** [comment]
For points, it's fairly straight-forward. We sampled random points from the instance segmentation mask of coco.

For scribbles, we first generate the skeleton from instance mask using opencv-function, please check this [link](https://scikit-image.org/docs/dev/auto_examples/edges/plot_skeleton.html). We then randomly take a connected path from it. 

If you have a new set of data and instance segmentation masks are missing, the best way to do it might be manual annotation? The original motivation of these synthetic partial labels is to mimic human annotation.

**Comment by lzl2040** [comment]
> For points, it's fairly straight-forward. We sampled random points from the instance segmentation mask of coco.
> 
> For scribbles, we first generate the skeleton from instance mask using opencv-function, please check this [link](https://scikit-image.org/docs/dev/auto_examples/edges/plot_skeleton.html). We then randomly take a connected path from it.
> 
> If you have a new set of data and instance segmentation masks are missing, the best way to do it might be manual annotation? The original motivation of these synthetic partial labels is to mimic human annotation.

Can you provide the code about how to generate the scribbles?
