### ISSUE TITLE
generate proposals and their scores for my own dataset

### ISSUE THREAD

**Issue by heboyong** [NVlabs/wetectron#38]
How to generate proposals and their scores for my own dataset as voc dataset?

**Comment by vipbze** [comment]
Did you achieve 54.9 AP on VOC07 dataset based on this git?

**Comment by jason718** [comment]
For proposal generation, you can use Selevtive-search, Edge-boxes or MCG.

For scores, you need to re-train a model and do inference. You can also use our model the classes of your dataset are overlapped with voc or coco.
