### ISSUE TITLE
Adapt solver's parameters to ngpus and iter_size

### ISSUE THREAD

**Issue by huyvvo** [NVlabs/wetectron#40]
Hi, thank you for the great work.

I would like to run the code without CDB but do not have access to multiple GPUs, so I intend to increase iter_size to have better gradients. Could you suggest an adaption of the solver's parameters to the new num_gpus and iter_size?

Thank you.

**Comment by jason718** [comment]
this is an empirical question. Unfortunately I didn't test it before. hard to suggest something meaningful.
