### ISSUE TITLE
When using concrete drop block, do you need additional loss term?

### ISSUE THREAD

**Issue by abeyang00** [NVlabs/wetectron#43]
Hi,

Thank you for the wonderful work.
I have a question about concrete drop block.

When you incorporate concrete drop block term, do you need additional loss term for distribution such as KL divergence 
or loglikelihood?

I'm asking because gumbel noise is sampled from distribution so perhaps KL divergence is needed like Variational AutoEncoder?

Thank you in advance

**Comment by jason718** [comment]
We didn't, but I think you raised a valid points. Maybe it's worthy trying.
