### ISSUE TITLE
About base_lr

### ISSUE THREAD

**Issue by suilin0432** [NVlabs/wetectron#46]
Why the base_lr is 0.01 in this framework, which is so big. I wonder that other frameworks often set base_lr as 0.001.
Thanks a lot~

**Comment by jason718** [comment]
we followed the setting in detectron2.

**Comment by suilin0432** [comment]
Fine... 
This is really a good job that the Mist algorithm works well when I transfer the design to my codebase with slightly modification.
But it's really strange that the performance could drop such a lot when using gpus less than 8 with the same batch_size settings and the performance is influnced by the random seed seriously in my experiments. I compare this codebase with others and I do not find any serious problem, so I guess maybe influnced by the large base_lr or the initialization strategy. I believe wetectron will be a popular framework for WSOD if you could refine details to make it more stable~

By the way, could you please offer a setting about the vanilla WSDDN, i have tried several times and the performance is not good.
Thanks a lot~
