### ISSUE TITLE
selective search strategy

### ISSUE THREAD

**Issue by liaorongfan** [NVlabs/wetectron#48]
when I try personal dataset such as mask detection or ship detection, I generate about 1~2K selective search boxes but the detection result will produce many false positives resulting in a terrible mAP value. I wonder if there is an appropriate strategy in selective search method generating proposal boxes

**Comment by jason718** [comment]
I'm not super familiar with this part. We used SS/MCG proposals that people already computed. We didn't do this part from scratch.
