### ISSUE TITLE
Dataset with bboxes and tags only

### ISSUE THREAD

**Issue by glemarivero** [NVlabs/wetectron#49]
Hi, I'm using your framework to see If I can train a model using a mixture of images with bboxes, and others with only the tag.
I'm using COCO format.
I'm having some issues with the annotations that don't have any bounding boxes, only tags:
```
ERROR: Iteration=1 || Image Ids used for training (845, 658, 738, 549) || targets Length=[9, 4, 0, 0]
```
What is the correct way to train this? Do you have an example of the config file, and what an annotation with no bbox should look like? (keys and values)

Thanks!

**Comment by jason718** [comment]
can you show me the complete error message? Which line of code does it complain?

You can create a dummy box for these ones with tags only. But this is somewhat weird to me as our code works for tag-only setting. Might be more informative if you can tell me where does this error occur.

**Comment by raghavgoyal14** [comment]
Hi @jason718, piggy-backing on this thread, is there a way to specify mix-supervision and train models with those? I'm trying to reproduce Table 6 of your ECCV paper. I cannot seem to find any part of your code which facilitate that, except specifying only tags, points, scribbles or boxes for supervision.

Thanks in advance!

**Comment by jason718** [comment]
@raghavgoyal14  Unfortunately this code isn't containing part you mentioned. But I think the unit functions for each single label are there (e.g., https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/modeling/roi_heads/weak_head/roi_sampler.py#L219, https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/data/datasets/coco.py#L160, https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/modeling/roi_heads/weak_head/loss.py#L195). The rest is to create a mixed dataset and set the flags to something similar as 
https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/modeling/roi_heads/weak_head/loss.py#L197

**Comment by raghavgoyal14** [comment]
Thank you @jason718 for such a detailed reply!
I just have one more question regarding the loss for unlabelled data. I cannot seem to find the code for entropy regularization and self-ensembling mentioned in Section 3.1 of your paper. 

![Screen Shot 2021-07-28 at 10 28 40 AM](https://user-images.githubusercontent.com/2176778/127266233-929953d7-ddf2-434d-af78-9a40f3c18437.png)

It would be awesome if you can point me to the relevant part of the code. Thanks!
