### ISSUE TITLE
About Corloc

### ISSUE THREAD

**Issue by PURE-melo** [NVlabs/wetectron#51]
Hi, Thanks for your nice code. Could you share the code for calculating Corloc? Thank you very much!

**Comment by jason718** [comment]
we have it here: https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/data/datasets/evaluation/voc/__init__.py#L27

**Comment by dingjietao** [comment]
> we have it here:
> 
> https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/data/datasets/evaluation/voc/__init__.py#L27

how to use the code to calculate CorLoc？
