### ISSUE TITLE
re-training fast-rcnn

### ISSUE THREAD

**Issue by jinhseo** [NVlabs/wetectron#53]
Hi, thank you for sharing your great work.

For the re-training supervision, I reckon you might follow previous works.

Is it involved in this repo? (Pseudo gt generation for re-training) 

If not, can u give us any details or the code you referred to?

**Comment by jason718** [comment]
Sorry, this repo doesn't contain that. 

I think the author of OICR has a repo: https://github.com/ppengtang/fast-rcnn . Even though it's in caffe, but the changes are pretty straight-forward. You can check the commit history to see what they did.
