### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by dingjietao** [NVlabs/wetectron#55]
1. i do not where to put pretrained weights--voc07_vgg16.pth
2. when i run the command：
“
export NGPUS=8
python -m torch.distributed.launch --nproc_per_node=$NGPUS tools/test_net.py \
    --config-file "configs/voc/V_16_voc07.yaml" TEST.IMS_PER_BATCH 8 \
    OUTPUT_DIR /path/to/output/dir \
    MODEL.WEIGHT /path/to/model
“
showed error：
AttributeError：module ‘torch._six' has no attribute 'PY3'

**Comment by jason718** [comment]
1. MODEL.WEIGHT /path/to/model
2. seems like a python/pytorch version mis-alignment issue. Don't know the exact solution.

**Comment by dingjietao** [comment]
> 1. MODEL.WEIGHT /path/to/model
> 2. seems like a python/pytorch version mis-alignment issue. Don't know the exact solution.

thank you！
