### ISSUE TITLE
Ensembling and number of students

### ISSUE THREAD

**Issue by vadimkantorov** [NVlabs/wetectron#57]
Hi @jason718!

I can't find in the code mentioning of multiple students or number of student layers. Is it actually `1`?

In the paper you mention that self-ensembling is used, but I also could not find what is the value of `N` :(
```
Self-ensembling. We follow [46, 45] to stack multiple student blocks to improve performance.
As shown in Fig. 2, the first pseudo-label Rˆ1 is generated from the teacher branch, and then the student block N generates pseudolabel RˆN for the next student block N + 1.
This technique is similar to the self-ensembling method [26].
```
I think the original OICR [46] used 3 students...

Thank you!

**Comment by vadimkantorov** [comment]
Found, it's N=3 https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/modeling/roi_heads/weak_head/roi_weak_predictors.py#L125

Because of very indirect model building via configs, it's hard to trace what gets called in the end :(

**Comment by jason718** [comment]
please see this line:
https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/modeling/roi_heads/weak_head/roi_weak_predictors.py#L67
https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/modeling/roi_heads/weak_head/roi_weak_predictors.py#L108
in loss:
https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/modeling/roi_heads/weak_head/loss.py#L154
during inference:
https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/modeling/roi_heads/weak_head/weak_head.py#L109

**Comment by vadimkantorov** [comment]
Haha, you were so fast, we posted at the same second! Thank you!
