### ISSUE TITLE
Learning only with Image level labels

### ISSUE THREAD

**Issue by Thomas-Malchers** [NVlabs/wetectron#58]
I am trying to learn only with image level labels. Whenever I start the training, I receive the error message at the beginning of the loop that the images could not be used since their target length equals 0. I provide all the images and their annotations in coco format. Each annotation only consists of a bounding box of zeros but includes a category_id representing the image class.

What is the correct format that needs to be provided in order to learn just from image level labels? Do I need to adjust the cfg file or the defaults.py/ paths_catalog.py?

Is it even possible to learn only using image level labels? For evaluation I do have a set ready to go with bounding box labels as well...

Thanks in advance for your help :)

**Comment by jason718** [comment]
not sure what you are confused for.

For example, on coco we used the original annotation file: https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/config/paths_catalog.py#L23,  which supports to train tag-only (image-level labels) models.
