### ISSUE TITLE
Batch size setting: per gpu or total?

### ISSUE THREAD

**Issue by vadimkantorov** [NVlabs/wetectron#59]
The paper mentions: `The batch size and initial learning rate is set to 8 and 0.01 on VOC 2007; 16 and 0.02 on
VOC 2012.`

This is total batch size, right? Then it is divided per GPUs, right? And I found that SyncBatchNorm is not used, so maybe that's another source of randomness when using smaller number of GPUs.

**Comment by jason718** [comment]
yep, that's the total batch size. --> 1 or2 image per GPU

we didn't use SyncBatchNorm mainly to follow prior work. but seems like it's unnecessary, and indeed that cause randomness.
