### ISSUE TITLE
Please modify the statement of the paper

### ISSUE THREAD

**Issue by anonymousiccv** [NVlabs/wetectron#6]
I think more than one person should have received such reviews: The paper [your cvpr20 paper] has better results and **has released the code**, why not compare with it. It’s the deadline for CVPR2021 again soon. Since you have post on the manuscript and arXiv that you have already released the codes half a year ago. I think you have the responsibility and obligation to inform readers in a more conspicuous position that the code of this paper has not been made public so far.

**Comment by jason718** [comment]
Sorry again, I'm sad that your review actually said that. 

We actually changed our latest arxiv version quite a while ago saying that we will release it under this repo.
