### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by vadimkantorov** [NVlabs/wetectron#61]
Hi! I'm building a derived codebase, for that having a minimal starting codebase is very desirable. Do I understand correctly that the following codes are not actually needed/used and can be safely deleted:

- https://github.com/NVlabs/wetectron/tree/master/wetectron/layers/dcn
- https://github.com/NVlabs/wetectron/tree/master/wetectron/modeling/roi_heads/keypoint_head
- https://github.com/NVlabs/wetectron/tree/master/wetectron/modeling/roi_heads/mask_head
- https://github.com/NVlabs/wetectron/tree/master/wetectron/modeling/rpn/retinanet
- https://github.com/NVlabs/wetectron/blob/master/wetectron/modeling/backbone/fbnet.py, https://github.com/NVlabs/wetectron/blob/master/wetectron/modeling/backbone/fbnet_builder.py, https://github.com/NVlabs/wetectron/blob/master/wetectron/modeling/backbone/fbnet_modeldef.py
- https://github.com/NVlabs/wetectron/blob/master/wetectron/modeling/backbone/fpn.py
- https://github.com/NVlabs/wetectron/blob/master/wetectron/utils/c2_model_loading.py

Thanks!

**Comment by jason718** [comment]
I didn't test, but all these seems to be irrelevant. The only exception is the last one, it might related to pre-trained model loading?
