### ISSUE TITLE
Strongly-supervised config (upper bound)

### ISSUE THREAD

**Issue by vadimkantorov** [NVlabs/wetectron#62]
If you have it, could you please publish also an upper-bound strongly-supervised object detection config? (i guess one with proposals, another with RPN?) (as found in tables 1 and 2)

**Comment by jason718** [comment]
we don't recommend doing that using this repo. As you should test these numbers using Detectron2. We changed some stuff here, and Detectron2 also gets improved a lot over last few years. So that we cannot guarantee the supervised performance can still match up.
