### ISSUE TITLE
Regression in refinement modules

### ISSUE THREAD

**Issue by vadimkantorov** [NVlabs/wetectron#63]
Hi @jason718.

Could you please explain how/where bbox regression is applied in refinement branches?

How final bbox coordinates are computed in inference?

I've found the code place https://github.com/NVlabs/wetectron/blob/master/wetectron/modeling/roi_heads/weak_head/weak_head.py#L120, but I don't understand what are the CLS-AVG, AVG, UNION

I've found that AVG is used in configs. Does it mean that regresed coordinates are averaged between all student branches? Are box proposals from the teacher branch included in the average? (my current understanding is that it is not, and the original proposals are only used as reference for bbox decoding)

How are accuracies changing if one takes just 1) the output of main branch, 2) output of each refinement branch?

**Comment by jason718** [comment]
AVG means we use the average of three  student heads. The teacher branch doesn't predict bbox and hence not used.

1. if you only take from main branch, that is essentially as selecting from the proposals. The performance will drop around 3% if I recall correctly.
2. if I use one of the three student, the performance will slightly hurts but not too much. Once it converged, these three guys perform pretty much the same.

**Comment by vadimkantorov** [comment]
Thanks for your answers!
