### ISSUE TITLE
How to map proposals from pkl to images?

### ISSUE THREAD

**Issue by vadimkantorov** [NVlabs/wetectron#64]
E.g. `SS-voc_2007_train-boxes.pkl` has the following keys: `['boxes', 'scores', 'indexes']`.

What are the `indexes`? How to map these indexes to image file names? 

Basically I'd like to load these proposals to my own method.

How does one map proposals from train and test to trainval? 

Thanks!

**Comment by jason718** [comment]
for VOC these are image ids, for example
``` 
proposal['indexes'][:20]
[12, 17, 23, 26, 32, 33, 34, 35, 36, 42, 44, 47, 48, 61, 64, 66, 73, 77, 78, 83]
```

means image 
```
000012.jpg, 000017.jpg, ...
```
https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/data/datasets/voc.py#L75

https://github.com/NVlabs/wetectron/blob/44e6fa95aee07d6722a62af56f016a3ae99bd8a6/wetectron/data/datasets/voc.py#L88

**Comment by vadimkantorov** [comment]
Got it! Thanks!
