### ISSUE TITLE
[question] Different distributed sampler compared to PyTorch core

### ISSUE THREAD

**Issue by vadimkantorov** [NVlabs/wetectron#65]
PyTorch core one splits the whole dataset in interleaved fashion:
https://github.com/pytorch/pytorch/blob/d5988c5eca0221e9ef58918e4f0b504940cb926a/torch/utils/data/distributed.py#L116
`indices = indices[self.rank:self.total_size:self.num_replicas]`

Wetectron returns them in sequential chunks:
https://github.com/NVlabs/wetectron/blob/69436c0c6bb77e8dddb6f3f2b5d912f0d1ecd8fb/wetectron/data/samplers/distributed.py#L57
`indices = indices[offset : offset + self.num_samples]`

Was it important? Or do you have any insight why this fashion was used?

**Comment by jason718** [comment]
probably not. We used this function from maskrcnn-benchmark and didn't make any changes/
