### ISSUE TITLE
NumPy vs PyTorch argmax

### ISSUE THREAD

**Issue by vadimkantorov** [NVlabs/wetectron#68]
At https://github.com/NVlabs/wetectron/blob/master/wetectron/modeling/roi_heads/weak_head/pseudo_label_generator.py#L54-L57 mentions that `pytorch and numpy argmax perform differently`. Do you have any comment about this difference? This could only matter for exactly same overlaps. Does it affect the accuracy?

**Comment by jason718** [comment]
yep, it  only matters for exactly same overlaps. 

Accuracy-wise, I didn't recall. I was transferring from an old code base (caffe?) and this was my attempt to make sure everything stay exactly the same.
