### ISSUE TITLE
Own Dataset

### ISSUE THREAD

**Issue by BlueBlueFF** [NVlabs/wetectron#7]
If i want use my own dataset，which kind of proposal is better？MCG or SS are matlab version，do you have some advices？

**Comment by jason718** [comment]
Unfortunately all these proposal methods are pretty old and the original code are almost all matlab based. For SS, there are some python repro like [this one](https://github.com/AlpacaDB/selectivesearch) or [this](https://github.com/belltailjp/selective_search_py). 

In most cases, MCG performs slight better as it comes later than SS. If you want to get high perf, probably use MCG is better.
