### ISSUE TITLE
COCO training with less than 8 GPU?

### ISSUE THREAD

**Issue by meunal** [NVlabs/wetectron#76]
Hi,

First of all, thanks a lot for the repo! I have been trying to run your COCO17 experiment with 2 GPUs but the same batch size of 8, and the results come out very bad each time. However, it is not the case when I use OICRPredictor without regression. Can it be about a bug such that MIST-associated losses are not properly reduced when a GPU gets more than one image?

Best,

**Comment by jason718** [comment]
it should be reduced properly since the same code works for pascal voc on multi-gpu with bs=2. I wouldn't suggest you using 2 gpu though since the training is very slow even using 8 gpu. I myself never tested on 2 gpu setting.
