### ISSUE TITLE
Training UFO^2

### ISSUE THREAD

**Issue by saratrajput** [NVlabs/wetectron#79]
Hi. Thank you for your work. I've been through both of your papers, Wetectron and UFO^2.

I was wondering if there is any difference in training a UFO^2 model with custom data compared to Wetectron. Or does this repository have training code for only Wetectron?

Sorry for bunching multiple questions here, but in essence, I would like to know if there are any guidelines to train a UFO^2 model with data having different types of annotations as mentioned in the paper. And would I need to generate object proposals for my custom data?

**Comment by jason718** [comment]
Sorry we didn't try this. hard to give some useful suggestions. We only tested on standard detection dataset, ie., pascal/coco
