### ISSUE TITLE
Pseudo label generator max score | Train wetectron on custom data

### ISSUE THREAD

**Issue by saratrajput** [NVlabs/wetectron#80]
Hello. Thank you for your work on Wetectron and UFO^2. I'm trying to train the model on my custom data. I have used Edgeboxes for generating the proposals. However, after following the steps given in README, I'm running into the following error:
```
File "/home/user/wetectron/wetectron/modeling/roi_heads/weak_head/pseudo_label_generator.py", line 43, in __call__
    k_ind[:, 0] = 1 # always take the one with max score
IndexError: index 0 is out of bounds for dimension 1 with size 0
```
I wondered if I needed to adjust the max score and NMS threshold. Please let me know if you have any tips.

**Comment by jason718** [comment]
sorry, hard to know what's happening here. We didn't test on custom data, and edgeboxes is also not used for our experiments.
