### ISSUE TITLE
local variable 'cfg' referenced before assignment

### ISSUE THREAD

**Issue by SongYii** [NVlabs/wetectron#9]
Traceback (most recent call last):
  File "tools/train_net.py", line 303, in <module>
    main()
  File "tools/train_net.py", line 238, in main
    cfg.merge_from_file(args.config_file)
UnboundLocalError: local variable 'cfg' referenced before assignment
Thank you for your code, the above error occurred when I was training, what should I do?

**Comment by jason718** [comment]
seems like you have some path issue that `cfg` is not properly imported form [here](https://github.com/NVlabs/wetectron/blob/3ce98d302d18e3ad07e23954259851180def66b7/tools/train_net.py#L17).

have you runed `python setup.py build develop` in installations step

?

**Comment by SongYii** [comment]
The original code can run, but the error will appear after Added ITER_SIZE parameter (#8). I tried `python setup.py build develop` , but the latest code still can’t run. The problem seems to be here    [https://github.com/NVlabs/wetectron/blob/3ce98d302d18e3ad07e23954259851180def66b7/tools/train_net.py#L240](url)

**Comment by jason718** [comment]
ah, this is a new PR we merged yesterday. I didn't fully test it. Please use the code from the 1st commit, I'll fix this later.

Thanks for pointing out.

**Comment by jason718** [comment]
fixed.
